### ISSUE TITLE
Why should I use this lib?

### ISSUE THREAD

**Issue by Alpine418** [selective-php/container#1]
What are the befenits of this lib? Why should I use this one, instead of the more known ones?

**Comment by odan** [comment]
This library is a simple PSR-11 container implementation. The benefits are...

* No dependencies from other libraries (except the PSR-11 interfaces)
* Faster than PHP-DI and thephpleague/container
* Autowiring mimics the behavior of PHP-DI. So moving to PHP-DI is quite easy.
* Simple usage

The advantages of using PHP-DI are:

* Big community and business support
* Much more features (but most people don't need all of them)
* Caching. Works only when you hard-wire your dependencies. I prefer autowiring as much as I can. Therefore, caching brings no performance gain (and a lot caching issues)

**Comment by Alpine418** [comment]
Thank you for your extended response. 

I will give your lib a try in my current project. I also prefer autowiring and a low number of dependencies. 👍
