### ISSUE TITLE
[Deprecated] Method ReflectionParameter::getClass()

### ISSUE THREAD

**Issue by DakinQuelia** [selective-php/container#5]
Hello,

In php 8.x I get this error : 

`Deprecated : Method ReflectionParameter::getClass() is deprecated in I:\Laragon\www\corvanis\vendor\selective\container\src\Resolver\ConstructorResolver.php on line 102`

How fix it ?

Thanks for reply.

Best regards

**Comment by odan** [comment]
Hi @DakinQuelia Thanks for reporting. I will try to fix it.

* https://php.watch/versions/8.0/deprecated-reflectionparameter-methods

**Comment by DakinQuelia** [comment]
Thanks for reply. :)

I appreciate your component Selective/Container. It's good job. 

Best regards

**Comment by odan** [comment]
It should be fixed now in the latest version.

**Comment by DakinQuelia** [comment]
Thanks. :)
